version: '3.8'
services:
  php:
    image: php:8.1-apache
    container_name: my_php_app
    volumes:
    - ./src:/var/www/html
    - ./PHPMailer:/var/www/html/PHPMailer
    - ./000-default.conf:/etc/apache2/sites-available/000-default.conf

    ports:
      - "8080:80"
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile # Đảm bảo là Dockerfile được xây dựng

  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: barber_management
      MYSQL_USER: barber
      MYSQL_PASSWORD: barber_pass
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
