version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 22032003
      MYSQL_DATABASE: HH_Movie
      MYSQL_USER: huydev
      MYSQL_PASSWORD: 29032003
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
